[package]
name = "stdscore_GUI"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
egui_extras = { version = "0.27", features = ["image"] }
scraper = "0.19"
regex = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }

# 读取拖拽文件内容（仅在某些平台需要）
rfd = "0.14"
