name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin]

    steps:
    - uses: actions/checkout@v4

    - name: Build and Upload with rust-build
      uses: rust-build/rust-build.action@v1.4.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        # 不打包 zip/tar，直接上传二进制
        ARCHIVE_TYPES: ""
        # 自定义上传的文件名（Release 页面里显示的名字）
        ARCHIVE_NAME: mytool-${{ matrix.target }}${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
        # 如果需要 strip/UPX 压缩，可以加上
        MINIFY: false
